/** Static drug name suggestions for prescription auto-complete.
 *  This is a UI-only convenience list, not a live database query.
 *  Replace with `supabase.from('medication_master').select('*')` when the table exists. */
export const PRESCRIPTION_DRUG_LIST: Array<{ medicineName: string; genericName?: string }> = [
  { medicineName: 'Paracetamol', genericName: 'Paracetamol' },
  { medicineName: 'Amoxicillin', genericName: 'Amoxicillin' },
  { medicineName: 'Amoxicillin + Clavulanic Acid', genericName: 'Co-amoxiclav' },
  { medicineName: 'Cephalexin', genericName: 'Cephalexin' },
  { medicineName: 'Azithromycin', genericName: 'Azithromycin' },
  { medicineName: 'Clarithromycin', genericName: 'Clarithromycin' },
  { medicineName: 'Ciprofloxacin', genericName: 'Ciprofloxacin' },
  { medicineName: 'Levofloxacin', genericName: 'Levofloxacin' },
  { medicineName: 'Metronidazole', genericName: 'Metronidazole' },
  { medicineName: 'Clindamycin', genericName: 'Clindamycin' },
  { medicineName: 'Doxycycline', genericName: 'Doxycycline' },
  { medicineName: 'Ibuprofen', genericName: 'Ibuprofen' },
  { medicineName: 'Mefenamic Acid', genericName: 'Mefenamic Acid' },
  { medicineName: 'Naproxen', genericName: 'Naproxen' },
  { medicineName: 'Celecoxib', genericName: 'Celecoxib' },
  { medicineName: 'Diclofenac', genericName: 'Diclofenac' },
  { medicineName: 'Omeprazole', genericName: 'Omeprazole' },
  { medicineName: 'Pantoprazole', genericName: 'Pantoprazole' },
  { medicineName: 'Esomeprazole', genericName: 'Esomeprazole' },
  { medicineName: 'Ranitidine', genericName: 'Ranitidine' },
  { medicineName: 'Metoclopramide', genericName: 'Metoclopramide' },
  { medicineName: 'Ondansetron', genericName: 'Ondansetron' },
  { medicineName: 'Losartan', genericName: 'Losartan' },
  { medicineName: 'Amlodipine', genericName: 'Amlodipine' },
  { medicineName: 'Metoprolol', genericName: 'Metoprolol' },
  { medicineName: 'Carvedilol', genericName: 'Carvedilol' },
  { medicineName: 'Enalapril', genericName: 'Enalapril' },
  { medicineName: 'Atorvastatin', genericName: 'Atorvastatin' },
  { medicineName: 'Rosuvastatin', genericName: 'Rosuvastatin' },
  { medicineName: 'Simvastatin', genericName: 'Simvastatin' },
  { medicineName: 'Metformin', genericName: 'Metformin' },
  { medicineName: 'Glimepiride', genericName: 'Glimepiride' },
  { medicineName: 'Insulin Glargine', genericName: 'Insulin Glargine' },
  { medicineName: 'Salbutamol', genericName: 'Salbutamol' },
  { medicineName: 'Montelukast', genericName: 'Montelukast' },
  { medicineName: 'Fluticasone', genericName: 'Fluticasone' },
  { medicineName: 'Cetirizine', genericName: 'Cetirizine' },
  { medicineName: 'Loratadine', genericName: 'Loratadine' },
  { medicineName: 'Fexofenadine', genericName: 'Fexofenadine' },
  { medicineName: 'Dexamethasone', genericName: 'Dexamethasone' },
  { medicineName: 'Prednisone', genericName: 'Prednisone' },
  { medicineName: 'Hydrocortisone', genericName: 'Hydrocortisone' },
  { medicineName: 'Ferrous Sulfate', genericName: 'Ferrous Sulfate' },
  { medicineName: 'Folic Acid', genericName: 'Folic Acid' },
  { medicineName: 'Vitamin B Complex', genericName: 'Vitamin B complex' },
  { medicineName: 'Vitamin C', genericName: 'Ascorbic acid' },
  { medicineName: 'Calcium Carbonate', genericName: 'Calcium carbonate' },
  { medicineName: 'Multivitamins', genericName: 'Multivitamins' },
  { medicineName: 'Tramadol', genericName: 'Tramadol' },
  { medicineName: 'Gabapentin', genericName: 'Gabapentin' },
  { medicineName: 'Diazepam', genericName: 'Diazepam' },
  { medicineName: 'Clonazepam', genericName: 'Clonazepam' },
  { medicineName: 'Sertraline', genericName: 'Sertraline' },
  { medicineName: 'Fluoxetine', genericName: 'Fluoxetine' },
  { medicineName: 'Furosemide', genericName: 'Furosemide' },
  { medicineName: 'Spironolactone', genericName: 'Spironolactone' },
  { medicineName: 'Warfarin', genericName: 'Warfarin' },
  { medicineName: 'Clopidogrel', genericName: 'Clopidogrel' },
  { medicineName: 'Aspirin', genericName: 'Aspirin' },
  { medicineName: 'Bisoprolol', genericName: 'Bisoprolol' }
];
